#!/usr/bin/env bash
# Regression test: scan tests/samples and compare EVERY result with
# tests/expected.txt. Fails on a missed sample, an unexpected finding, a
# changed severity, a lost decoded domain, or a --verify DIFF.
#
#   bash tests/run.sh            # check
#   bash tests/run.sh --update   # rewrite expected.txt from the current output
#                                # (review the git diff before committing!)
#
# expected.txt lines:  <high|med|low|ignored|domain>  <CHECK|domain>  <path>
set -euo pipefail
export LC_ALL=C
here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
scanner="$here/../fixed-malscan.sh"
expected="$here/expected.txt"
tmp=$(mktemp -d); trap 'rm -rf -- "$tmp"' EXIT

cd -- "$here/samples"
rc=0; bash "$scanner" -k --no-color -v . > "$tmp/out" 2>&1 || rc=$?
if [[ $rc != 1 ]]; then
  echo "FAIL: expected exit 1 (findings), got $rc"; tail -20 "$tmp/out"; exit 1
fi

awk '
  /SUMMARY/ { s = 1; next }
  # live findings (-v), before the summary:
  #   [SEV] path:line  CHECK     |   [SEV] path  note · CHECK
  !s && /^\[(HIGH|MED|LOW)\]/ {
    sev = tolower(substr($1, 2, length($1) - 2)); p = $2; sub(/:[0-9]+$/, "", p)
    print sev, $NF, p; next }
  #   path [CHECK,CHECK] - reason          (ignored, summary with -v)
  s && /^    [^ ].* \[[A-Z0-9_,]+\] - / {
    p = $1; ids = $2; gsub(/[][]/, "", ids)
    n = split(ids, a, ","); for (i = 1; i <= n; i++) print "ignored", a[i], p; next }
  #   domain  <- path                       (Hidden domains)
  s && /^  [^ ]+  <- / { print "domain", $1, $3 }
' "$tmp/out" | sort -u > "$tmp/got"

if [[ ${1:-} == --update ]]; then
  { echo "# <high|med|low|ignored|domain> <CHECK|domain> <path>  (generated by run.sh --update)"
    cat "$tmp/got"; } > "$expected"
  echo "updated $expected ($(wc -l < "$tmp/got") results) - review: git diff tests/expected.txt"
  exit 0
fi

grep -v '^#' "$expected" | sort -u > "$tmp/want"
fail=0
if ! diff -u "$tmp/want" "$tmp/got" > "$tmp/diff"; then
  fail=1
  echo "FAIL: results differ from tests/expected.txt  (- expected, + got)"
  grep -E '^[-+][a-z]' "$tmp/diff"
fi

bash "$scanner" -k --no-color --verify . > "$tmp/verify" 2>&1 || true
if grep -q 'DIFF' "$tmp/verify"; then
  fail=1; echo "FAIL: --verify shows a DIFF (a prefilter drops matches)"
  grep -A3 'DIFF' "$tmp/verify"
fi

(( fail )) && exit 1
echo "OK: $(wc -l < "$tmp/got") expected results, --verify clean"
